### ISSUE TITLE
ProjectInfo miss toString()

### ISSUE THREAD

**Issue by magaofei** [uwolfer/gerrit-rest-java-client#129]
ProjectInfo miss toString() method

**Comment by EFregnan** [comment]
Thank you for pointing this out. 

Classes in the _src/main/java/com/google/gerrit/_ folder are taken directly from the official Gerrit source code.
I checked their master branch and the ProjectInfo class ([here](https://gerrit.googlesource.com/gerrit/+/refs/heads/master/java/com/google/gerrit/extensions/common/ProjectInfo.java)) does not contain a _toString()_ method there as well 

Since the ProjectInfo class in this project has to be the same as the one in the official Gerrit release, maybe you could open this issue in Gerrit.
If they decide to modify the class in their code, we will adopt the change here too.

**Comment by uwolfer** [comment]
@EFregnan: Thanks for your feedback - fully agree.

@magaofei Thanks for reporting, but please open this report upstream: https://www.gerritcodereview.com/issues.html
