### ISSUE TITLE
Authentication: Only authenticate using /a

### ISSUE THREAD

**Issue by dennisandersen** [uwolfer/gerrit-rest-java-client#46]
Hi @uwolfer 

Would it be possible to provide some means of bypassing the authentication attempts towards /login and only use the rest api auth scheme as described in https://gerrit-review.googlesource.com/Documentation/rest-api.html#authentication by authenticating towards /a/**

**Comment by uwolfer** [comment]
@dennisandersen: When you do not pass credentials, it does not try to authenticate. Isn't this what you want?

**Comment by dennisandersen** [comment]
I do want to authenticate to eg /a/projects using digest/basic as described in the doc.. But i do not want the client to attempt any authentication towards /login to acquire a session cookie.

Reason being, that the gerrit server i'm working against does ldap authentication at the /login endpoint whereas authenticating at /a/projects requires the gerrit generated http password for the user. 

Just to give a litthe background. i'm using the sonar-gerrit jenkins plugin which in turn uses this client library. It in turn acquires login details for the REST endpoint from the jenkins gerrit trigger plugin.. The Gerrit trigger plugin for Jenkins will validate the REST credentials towards /a/ but when the sonar-gerrit plugin tries to submit review comments, the gerrit-rest-java-client verifies using the HTTP password against ldap.. Connection fails.

At the moment i have shortwired to circumvent calling tryGerritHttpFormAuth, tryGerritHttpAuth GerritRestClient.java such that gerritAuthOptional is always absent and it falls back to what i want :)

**Comment by uwolfer** [comment]
@dennisandersen: Thanks for your explanation - this makes sense of course.

**Comment by lanejo01** [comment]
I'm literally dealing with this today! The exact use case that @dennisandersen has is what i'm trying to solve. @dennisandersen any way you could send me a patch or post where you are doing this "shortwiring"?

**Comment by uwolfer** [comment]
@lanejo01: I think you can just change [GerritRestClient.java:182](https://github.com/uwolfer/gerrit-rest-java-client/blob/master/src/main/java/com/urswolfer/gerrit/client/rest/http/GerritRestClient.java#L182) to: `Optional<String> gerritAuthOptional = Optional.absent();`

I'm still not sure how to implement this. In most cases, caching the login (cookie which is received when sending auth data to "/login") is desired.

One really hacky way would be to prefix the username with some keyword like "no-cache:", like "no-cache:myuser". But I do not like this solution at all...
But adding an API for disabling login cache (and thus authenticate every request against "/a") would not help in most cases since this is a configuration thing (e.g. when using the Jenkins plugin which uses internally this library). So the user needs to decide how he wants to authenticate.

**Comment by cbaldacin** [comment]
I'm not sure this is 100% related with this issue but, why can't I perform these two operations bellow without having to login again between requests?

List<ChangeInfo> changes = gerritApi.changes().query("status:merged").withLimit(10).get();
// have to login again here
gerritApi.changes().id(changeid).comments();

**Comment by uwolfer** [comment]
@cbaldacin: The behavior your have described is expected. Since you have created the `GerritApi` with credentials, they are passed to the server with every request issued by the same instance of `GerritApi`.

**Comment by sstafford** [comment]
This has become a huge problem for me as well.  We have an environment where we use an LDAP service account for our Jenkins and Gerrit admin and automated activities.  This account is currently being locked almost daily due to calls from both our internal tools as well as what we suspect is the Jenkins Gerrit-Sonar plugin which is in use on at least one of our Jenkins instances.  I've submitted a pull request to suggest a new GerritAuthData constructor that would allow the caller to identify the password as a Gerrit HTTP password, causing the behavior of the GerritRestClient to skip calls to /login.

https://github.com/uwolfer/gerrit-rest-java-client/pull/70

I realize that this approach requires fixes to consumers of this API, such as Jenkins plugins, but I really didn't see a reasonable way to accomplish this change otherwise.  We tried fiddling around with various Gerrit configurations, as well as querying the Gerrit /config/server/info endpoint to try to make a more intelligent decision about what actions to take for authentication, but it all came back to the problem of needing to know whether the password being provided was a Gerrit HTTP Password token or a true password that could be used by the /login page.

If this pull request gets approved, I'll track down the gerrit sonar plugin that might also be causing the problem and submit a fix for that as well.

**Comment by uwolfer** [comment]
If anybody could test the patch provided by @sstafford (Thank you very much!), it would be nice.

If there are no objections, I'll merge it soon.

**Comment by dennisandersen** [comment]
I shall try to verify the change with my jenkins gerrit setup today.

**Comment by dennisandersen** [comment]
I have integrated the changes within the sonar-gerrit plugin and tried it out briefly.. This is a clean version of my current workaround. I say merge.. :+1:

**Comment by sstafford** [comment]
Once this commit has merged, I would also like to request a new release version be cut.  Once that is available I can submit a pull request to the Jenkins sonar-gerrit plugin to use the new constructor:

https://github.com/jenkinsci/sonar-gerrit-plugin/blob/master/src/main/java/org/jenkinsci/plugins/sonargerrit/SonarToGerritPublisher.java

I think that should solve the lock-out issues we're experiencing when using that plugin.

**Comment by uwolfer** [comment]
@sstafford: 0.8.11 is out. Thanks for your work.

**Comment by sstafford** [comment]
For those who are using the Jenkins sonar-gerrit-plugin and are experiencing LDAP account lockouts due to this bug, I have opened the following defect against that plugin.  There is a pull request listed in the defect comments which also provides a pull request for resolving the issue.

Jenkins sonar-gerrit-plugin defect:
https://issues.jenkins-ci.org/browse/JENKINS-42465

Jenkins sonar-gerrit-plugin pull request:
https://github.com/jenkinsci/sonar-gerrit-plugin/pull/17

**Comment by sebValiantys** [comment]
Shouldn't this issue be closed since [PR #70](https://github.com/uwolfer/gerrit-rest-java-client/pull/70) has been merged in 0.8.11 ? Or are there still issues pending on this matter ?
