### ISSUE TITLE
How to get change detail??

### ISSUE THREAD

**Issue by isha25** [uwolfer/gerrit-rest-java-client#69]
Hi,

What will be the code for viewing detail of a particular change?
How to use o option for using detailed_labels??

Tried this :
gerritApi.changes.id(cid).get()

But got exception: -o web_links not supported

Please help me getting detail of a change using this library

**Comment by uwolfer** [comment]
What's the version number of your Gerrit server?

**Comment by rohitthe** [comment]
gerrit version 2.9.3

**Comment by isha25** [comment]
My gerrit version is 2.9.3

**Comment by isha25** [comment]
Any update??

**Comment by uwolfer** [comment]
> My gerrit version is 2.9.3

The option `WEB_LINKS` is not supported with Gerrit 2.9. It got introduced for 2.10. You can try to pass `ListChangesOption` to your request instead of using default options. See `QueryRequest`.

`gerritApi.changes.query("change:yourchangeid).withOptions(...)...`

Please post the whole trace you get when using the call posted in your initial report.

> Any update??

Please keep in mind that this is an open source project which I do in my spare time only.

**Comment by isha25** [comment]
Hey I understand but need to sort this out urgently so thats why bit curious..

Anyways in withOptions() what all values can we pass..and how ??could you give me an example??

**Comment by uwolfer** [comment]
You can find all options here:
https://github.com/uwolfer/gerrit-rest-java-client/blob/master/src/main/java/com/google/gerrit/extensions/client/ListChangesOption.java

**Comment by isha25** [comment]
Thanks
